"""add delivery zones, order ratings, and product lifecycle

Revision ID: 340058b2a51e
Revises: 49b073385187
Create Date: 2026-08-30 10:15:51.748341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340058b2a51e'
down_revision: Union[str, None] = '49b073385187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This DB already has real order rows (local dev and Render/production
    # share it - see CLAUDE.md's Neon DB note), so a NOT NULL column can't
    # just be added bare - server_default='0' backfills every existing
    # order with delivery_fee=0 (correct: they were placed before delivery
    # zones existed, so no fee was ever charged) at the same time the
    # column is added, in one statement.
    op.create_table('delivery_zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_delivery_zone_fee_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order_ratings',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_order_rating_score_range'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('orders', sa.Column('delivery_zone_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'orders', 'delivery_zones', ['delivery_zone_id'], ['id'])
    op.add_column('products', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deactivated_at')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'delivery_zone_id')
    op.drop_table('order_ratings')
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
