"""make cart guest_token unique only among active carts

Revision ID: 38dfc1b2fae7
Revises: 8d9f908bc773
Create Date: 2026-08-06 11:22:09.199221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dfc1b2fae7'
down_revision: Union[str, None] = '8d9f908bc773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carts_guest_token_key', 'carts', type_='unique')
    op.create_index('uq_carts_guest_token_active', 'carts', ['guest_token'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_carts_guest_token_active', table_name='carts', postgresql_where=sa.text("status = 'active'"))
    op.create_unique_constraint('carts_guest_token_key', 'carts', ['guest_token'])
    # ### end Alembic commands ###
