"""add customer addresses, staff must_change_password, rename inventory_manager to owner

Revision ID: 45bf0f5a35f2
Revises: fae7dd588a8d
Create Date: 2026-08-18 16:36:18.697969

Three unrelated-looking changes bundled together because they all came out
of the same frontend handoff round (2026-08-18): a new customer_addresses
table for the Address Book, a must_change_password flag for the new
first-login-reset flow, and renaming the staff_role enum's
'inventory_manager' label to 'owner'. The enum rename isn't something
--autogenerate can detect on its own (it diffs enum MEMBERSHIP, not
individual label spellings), so that part was added by hand.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf0f5a35f2'
down_revision: Union[str, None] = 'fae7dd588a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # RENAME VALUE (not "remove old, add new") is what makes every existing
    # staff_users row that already said 'inventory_manager' become 'owner'
    # automatically, with no separate UPDATE needed - Postgres just relabels
    # the enum member in place. Supported since PG10; Neon runs a modern
    # enough version for this to be transactional like the rest of this
    # migration.
    op.execute("ALTER TYPE staff_role RENAME VALUE 'inventory_manager' TO 'owner'")

    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default so this doesn't fail against the staff_users rows that
    # already exist (including the 34 stale test-fixture accounts) - every
    # existing row becomes must_change_password=false, same as
    # models.py's Python-side default for any row created after this.
    op.add_column('staff_users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_users', 'must_change_password')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
    op.execute("ALTER TYPE staff_role RENAME VALUE 'owner' TO 'inventory_manager'")
