"""add guest_token to orders

Revision ID: 8d9f908bc773
Revises: 6e336ac5877a
Create Date: 2026-08-05 21:20:43.316457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9f908bc773'
down_revision: Union[str, None] = '6e336ac5877a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'guest_token')
    # ### end Alembic commands ###
