"""create product images and variant attributes tables

Revision ID: b74fddbefc9e
Revises: 23ab3912efd6
Create Date: 2026-07-20 19:44:04.420234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74fddbefc9e'
down_revision: Union[str, None] = '23ab3912efd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_product_images_one_primary', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('variant_attributes',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('attribute_name', sa.String(length=50), nullable=False),
    sa.Column('attribute_value', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'attribute_name', name='uq_variant_attribute_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_attributes')
    op.drop_index('uq_product_images_one_primary', table_name='product_images', postgresql_where=sa.text('is_primary = true'))
    op.drop_table('product_images')
    # ### end Alembic commands ###
