"""replace delivery zones with divisions, areas, and pickup stations

Revision ID: d0ef9e4ae56d
Revises: 340058b2a51e
Create Date: 2026-08-30 21:12:55.217947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ef9e4ae56d'
down_revision: Union[str, None] = '340058b2a51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - reordered by hand: the
    # autogenerated version tried to drop_table('delivery_zones') BEFORE
    # dropping the orders.delivery_zone_id FK that still points at it,
    # which Postgres refuses ("cannot drop table because other objects
    # depend on it"). The old FK/column must go first; only THEN is
    # delivery_zones safe to drop. Same "drop the referencing side before
    # the referenced table" rule as the 2026-08-20 branches-removal
    # migration (see CLAUDE.md). This DB has real order rows already using
    # delivery_zone_id (today's UAT batch) - safe to drop anyway since
    # nothing downstream reads that column once this migration lands, and
    # every new column here is nullable (no backfill needed).
    op.create_table('delivery_divisions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regional_pickup_stations',
    sa.Column('major_town', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_regional_pickup_station_fee_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_areas',
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_delivery_area_fee_non_negative'),
    sa.ForeignKeyConstraint(['division_id'], ['delivery_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('delivery_division_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('delivery_area_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('regional_pickup_station_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('delivery_division_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_area_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('pickup_town', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_instructions', sa.String(length=500), nullable=True))
    op.drop_constraint('orders_delivery_zone_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_zone_id')
    op.create_foreign_key(None, 'orders', 'regional_pickup_stations', ['regional_pickup_station_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'delivery_divisions', ['delivery_division_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'delivery_areas', ['delivery_area_id'], ['id'])
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_zone_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_delivery_zone_id_fkey', 'orders', 'delivery_zones', ['delivery_zone_id'], ['id'])
    op.drop_column('orders', 'delivery_instructions')
    op.drop_column('orders', 'pickup_town')
    op.drop_column('orders', 'delivery_area_name')
    op.drop_column('orders', 'delivery_division_name')
    op.drop_column('orders', 'regional_pickup_station_id')
    op.drop_column('orders', 'delivery_area_id')
    op.drop_column('orders', 'delivery_division_id')
    op.create_table('delivery_zones',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fee', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_delivery_zone_fee_non_negative'),
    sa.PrimaryKeyConstraint('id', name='delivery_zones_pkey'),
    sa.UniqueConstraint('name', name='delivery_zones_name_key')
    )
    op.drop_table('delivery_areas')
    op.drop_table('regional_pickup_stations')
    op.drop_table('delivery_divisions')
    # ### end Alembic commands ###
