"""add district to orders

Revision ID: d68f504c3052
Revises: 38dfc1b2fae7
Create Date: 2026-08-06 19:39:37.264211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68f504c3052'
down_revision: Union[str, None] = '38dfc1b2fae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('district', sa.String(length=100), nullable=True))
    op.execute("UPDATE orders SET district = 'Unknown' WHERE district IS NULL")
    op.alter_column('orders', 'district', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'district')
    # ### end Alembic commands ###
