"""add redirect_url to payments

Revision ID: e5dfc75a77e8
Revises: fa8429cf025f
Create Date: 2026-07-21 11:08:31.783160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dfc75a77e8'
down_revision: Union[str, None] = 'fa8429cf025f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('redirect_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'redirect_url')
    # ### end Alembic commands ###
