"""create payments table

Revision ID: e76ccf631dfc
Revises: 084eccefade8
Create Date: 2026-07-20 15:54:15.719131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76ccf631dfc'
down_revision: Union[str, None] = '084eccefade8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'awaiting_payment', 'paid', 'failed', name='payment_status'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_reference', sa.String(length=150), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_payments_order_paid', 'payments', ['order_id'], unique=True, postgresql_where=sa.text("status = 'paid'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payments_order_paid', table_name='payments', postgresql_where=sa.text("status = 'paid'"))
    op.drop_table('payments')
    # ### end Alembic commands ###
